
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tv.blackarrow.cpp.webservice.impl;

import org.apache.logging.log4j.Logger;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import tv.blackarrow.cpp.webservice.scte130_5_2010.POISCancelCursorRequestType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISCancelCursorResponseType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISCreateCursorRequestType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISCreateCursorResponseType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISListNotificationRegistrationRequestType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISListNotificationRegistrationResponseType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISListQualifiersRequestType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISListQualifiersResponseType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISListSupportedFeaturesRequestType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISListSupportedFeaturesResponseType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISNotificationDeregisterRequestType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISNotificationDeregisterResponseType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISNotificationRegistrationRequestType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISNotificationRegistrationResponseType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISQueryRequestType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISQueryResponseType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.POISServer;
import tv.blackarrow.cpp.webservice.scte130_5_2010.ServiceCheckRequestType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.ServiceCheckResponseType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.ServiceStatusAcknowledgementType;
import tv.blackarrow.cpp.webservice.scte130_5_2010.ServiceStatusNotificationType;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-03-29T11:54:59.634-07:00
 * Generated source version: 2.5.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "POISServerService",
                      portName = "POISPortSoap",
                      targetNamespace = "http://www.scte.org/wsdl/130-5/2010/pois",
                      endpointInterface = "tv.blackarrow.cpp.webservice.scte130_5_2010.POISServer")
                      
public class POISServerImp implements POISServer {
    private static final Logger LOG = LogManager.getLogger(POISServerImp.class.getName());

	@Override
	public POISQueryResponseType poisQueryRequest(POISQueryRequestType request) {
		
		//TODO implementation
		
		return null;
	}

	@Override
	public POISNotificationRegistrationResponseType poisNotificationRegistrationRequest(
			POISNotificationRegistrationRequestType request) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public POISListSupportedFeaturesResponseType poisListSupportedFeaturesRequest(
			POISListSupportedFeaturesRequestType request) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public POISCancelCursorResponseType poisCancelCursorRequest(
			POISCancelCursorRequestType request) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public POISListQualifiersResponseType poisListQualifiersRequest(
			POISListQualifiersRequestType request) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ServiceCheckResponseType serviceCheckRequest(
			ServiceCheckRequestType request) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public POISCreateCursorResponseType poisCreateCursorRequest(
			POISCreateCursorRequestType request) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public POISNotificationDeregisterResponseType poisNotificationDeregisterRequest(
			POISNotificationDeregisterRequestType request) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public POISListNotificationRegistrationResponseType poisListNotificationRegistrationRequest(
			POISListNotificationRegistrationRequestType request) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ServiceStatusAcknowledgementType serviceStatusNotification(
			ServiceStatusNotificationType request) {
		// TODO Auto-generated method stub
		return null;
	}

}
